name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: centos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: init conda
      run: |
        source activate
    - name: create env
      run: |
        conda create --name table_ocr python=3.7.4 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
    - name: change env
      run: |
        conda activate table_ocr
    - name: config env
      run: |
        conda install paddlepaddle==2.4.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
        pip install "paddleocr==2.6.1.3" -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install opencv-python==4.6.0.66 -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install opencv-python-headless==4.8.0.74 -i https://pypi.tuna.tsinghua.edu.cn/simple 
        pip install opencv-contrib-python==4.6.0.66  -i https://pypi.tuna.tsinghua.edu.cn/simple 
        pip install Flask==2.2.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install shutilwhich -i https://pypi.tuna.tsinghua.edu.cn/simple
    - name: start run
      run: |
        conda deactivate 
        sh start.sh
      
